export const THEME = {
  colors: {
    background: '#F8F8F6',
    surface: '#FFFFFF',
    primaryAccent: '#FFC100',
    ctaGold: '#FBC900',
    cartBarBackground: '#FCF1D0',
    textPrimary: '#1C1C1E',
    textSecondary: '#71717A',
    textMuted: '#9E9EA7',
    border: '#E8E8E2',
    cardBorder: '#EFEFEA',
    veg: '#2E7D32',
    vegLight: '#E8F5E9',
    nonVeg: '#C62828',
    nonVegLight: '#FFEBEE',
    goldLight: '#FFF9E6',
    goldBorder: '#FFE082',
    badgeText: '#4A3B00',
    shadowColor: '#000000',
    divider: '#F0F0EB',
  },
  typography: {
    title: {
      fontSize: 18,
      fontWeight: '700',
      color: '#1C1C1E',
    },
    subTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: '#1C1C1E',
    },
    body: {
      fontSize: 13,
      fontWeight: '400',
      color: '#71717A',
    },
    price: {
      fontSize: 15,
      fontWeight: '700',
      color: '#1C1C1E',
    },
    badge: {
      fontSize: 11,
      fontWeight: '700',
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
  },
  borderRadius: {
    sm: 6,
    md: 10,
    lg: 14,
    xl: 20,
    round: 999,
  },
};
